# The Climate Sensor Grid Analyzer


### The Scenario: You are a climate data scientist. You have been handed a massive dataset from a satellite grid. To load the .npy file use np.load(“...”). The data is a 3D NumPy array structured as (Latitude, Longitude, Days), and the values inside represent the daily peak temperature in Celsius. You need to clean, analyze, and transform this data using only NumPy operations.
* Creating Arrays & Attributes: You load the provided climate dataset. You must inspect .shape, .ndim, and .dtype to understand how the geographical coordinates and the 31 days of the month are structured. Because you will be calculating temperature anomalies later, you also need to create a blank "baseline grid" of the exact same geographical dimensions using np.zeros().
* Indexing, Slicing & Masking: 
Slicing: The dataset covers the whole globe, but you only want to analyze a specific drought-prone region. Crop the data to specific latitude and longitude coordinates (e.g., climate_data[20:50, 70:120, :]).
* Indexing: Isolate a "snapshot" of the entire grid for exactly Day 15 to see a cross-section of global temperatures on that specific day.
* Masking: Data cleaning is required. A sensor glitch caused several locations to record impossible temperatures of -99°C. Create a boolean mask to find all instances of -99 and replace them with np.nan (Not a Number) so they don't skew your later calculations.
* Vectorization, Broadcasting & Ufuncs: 

  - Broadcasting: Your American stakeholders need the data in Fahrenheit. Convert the entire 3D array from Celsius to Fahrenheit in a single mathematical step ((data * 9/5) + 32) without writing a single for loop.
  - Ufuncs: To model a specific heat-stress index, apply a non-linear transformation to the temperature values using np.exp() and np.log() across the entire grid simultaneously.
* Math & Stats:

  - Find the absolute highest and lowest valid temperatures recorded anywhere on the grid during the month (np.nanmax, np.nanmin).

   - Calculate the average temperature for each specific sensor location across the entire month (using np.nanmean across the "Days" axis). This will collapse your 3D array into a 2D map showing the baseline climate for each coordinate!

* Creating Arrays & Attributes: You load the provided climate dataset. You must inspect .shape, .ndim, and .dtype to understand how the geographical coordinates and the 31 days of the month are structured. Because you will be calculating temperature anomalies later, you also need to create a blank "baseline grid" of the exact same geographical dimensions using np.zeros().


In [13]:
import numpy as np
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

climate_data = np.load("climate_data.npy")

print(climate_data.shape)
print(climate_data.size)
print(climate_data.ndim)
print(climate_data.dtype)
blank = np.zeros(img_arr.shape[:2])
print(blank)

[[[  4.3  41.8  27.6 ...  18.5 -17.   19.5]
  [ -8.9 -15.8  41.7 ...   1.1   5.3  -2.4]
  [ 33.9   3.2  -1.7 ... -12.2  26.4  29.5]
  ...
  [  1.8  13.1  14.6 ...   0.4  25.5  33.7]
  [ 27.5  44.3  -2.3 ...  34.3   5.9   9.1]
  [ 35.3  30.4  -1.3 ...  -8.3  23.1  23.7]]

 [[ -3.6   1.1  34.3 ...  -1.6  21.6  19.5]
  [-10.   -6.6  20.4 ...   8.7 -15.7   6.1]
  [ 29.7  39.5   6.9 ...  16.   26.7  38.3]
  ...
  [  3.7  14.2 -12.4 ... -16.9  31.    5. ]
  [-13.   29.6  35.2 ...  33.6  26.9  35.6]
  [  5.2 -12.5  34.8 ...   8.3  22.4  -6.7]]

 [[ 10.6  43.7  -7.3 ...  -1.7  29.7 -13.1]
  [ 39.6  38.2  39.1 ...  38.4   9.8   8.6]
  [ -8.6  42.9  -6.1 ...  31.4 -14.7  37.8]
  ...
  [ 32.2 -13.4  21.9 ...   1.1  12.8  44.6]
  [  8.3  14.1  25.2 ...  -9.9  15.   29.8]
  [ 44.2  37.5  36.2 ...   3.    5.6  39.6]]

 ...

 [[-12.7  40.9  -3.8 ... -13.    2.1  32.2]
  [ 12.1  27.3 -18.6 ...   5.1  41.1 -10.5]
  [ 37.6  14.2  17.8 ...  35.5  13.3  19.1]
  ...
  [ 28.1  11.5  25.2 ...  12.7   6.   38

* Indexing, Slicing & Masking: 
Slicing: The dataset covers the whole globe, but you only want to analyze a specific drought-prone region. Crop the data to specific latitude and longitude coordinates (e.g., climate_data[20:50, 70:120, :]).
* Indexing: Isolate a "snapshot" of the entire grid for exactly Day 15 to see a cross-section of global temperatures on that specific day.
* Masking: Data cleaning is required. A sensor glitch caused several locations to record impossible temperatures of -99°C. Create a boolean mask to find all instances of -99 and replace them with np.nan (Not a Number) so they don't skew your later calculations.



In [12]:
slicing = climate_data[20:50, 70:120 ,:]
day_15_snapshot = climate_data[:, : , 14] 

img_arr[img_arr == -99 ] = np.nan

print(slicing)
print(day_15_snapshot)
print(climate_data)


[[[  4.3  41.8  27.6 ...  18.5 -17.   19.5]
  [ -8.9 -15.8  41.7 ...   1.1   5.3  -2.4]
  [ 33.9   3.2  -1.7 ... -12.2  26.4  29.5]
  ...
  [  1.8  13.1  14.6 ...   0.4  25.5  33.7]
  [ 27.5  44.3  -2.3 ...  34.3   5.9   9.1]
  [ 35.3  30.4  -1.3 ...  -8.3  23.1  23.7]]

 [[ -3.6   1.1  34.3 ...  -1.6  21.6  19.5]
  [-10.   -6.6  20.4 ...   8.7 -15.7   6.1]
  [ 29.7  39.5   6.9 ...  16.   26.7  38.3]
  ...
  [  3.7  14.2 -12.4 ... -16.9  31.    5. ]
  [-13.   29.6  35.2 ...  33.6  26.9  35.6]
  [  5.2 -12.5  34.8 ...   8.3  22.4  -6.7]]

 [[ 10.6  43.7  -7.3 ...  -1.7  29.7 -13.1]
  [ 39.6  38.2  39.1 ...  38.4   9.8   8.6]
  [ -8.6  42.9  -6.1 ...  31.4 -14.7  37.8]
  ...
  [ 32.2 -13.4  21.9 ...   1.1  12.8  44.6]
  [  8.3  14.1  25.2 ...  -9.9  15.   29.8]
  [ 44.2  37.5  36.2 ...   3.    5.6  39.6]]

 ...

 [[-12.7  40.9  -3.8 ... -13.    2.1  32.2]
  [ 12.1  27.3 -18.6 ...   5.1  41.1 -10.5]
  [ 37.6  14.2  17.8 ...  35.5  13.3  19.1]
  ...
  [ 28.1  11.5  25.2 ...  12.7   6.   38

* Vectorization, Broadcasting & Ufuncs: 

   + Broadcasting: Your American stakeholders need the data in Fahrenheit. Convert the entire 3D array from Celsius to Fahrenheit in a single mathematical step ((data * 9/5) + 32) without writing a single for loop.

   + Ufuncs: To model a specific heat-stress index, apply a non-linear transformation to the temperature values using np.exp() and np.log() across the entire grid simultaneously.


In [15]:
temp_fahrenheit = (climate_data * 9/5 ) + 32 
temp_celsius = (climate_data - 32 ) * 5/9 
heat_stress = np.exp(np.log(climate_data + 10 ))

print(temp_fahrenheit)
print(temp_celsius)
print(heat_stress)


[[[ 39.74 107.24  81.68 ...  65.3    1.4   67.1 ]
  [ 15.98   3.56 107.06 ...  33.98  41.54  27.68]
  [ 93.02  37.76  28.94 ...  10.04  79.52  85.1 ]
  ...
  [ 35.24  55.58  58.28 ...  32.72  77.9   92.66]
  [ 81.5  111.74  27.86 ...  93.74  42.62  48.38]
  [ 95.54  86.72  29.66 ...  17.06  73.58  74.66]]

 [[ 25.52  33.98  93.74 ...  29.12  70.88  67.1 ]
  [ 14.    20.12  68.72 ...  47.66   3.74  42.98]
  [ 85.46 103.1   44.42 ...  60.8   80.06 100.94]
  ...
  [ 38.66  57.56   9.68 ...   1.58  87.8   41.  ]
  [  8.6   85.28  95.36 ...  92.48  80.42  96.08]
  [ 41.36   9.5   94.64 ...  46.94  72.32  19.94]]

 [[ 51.08 110.66  18.86 ...  28.94  85.46   8.42]
  [103.28 100.76 102.38 ... 101.12  49.64  47.48]
  [ 16.52 109.22  21.02 ...  88.52   5.54 100.04]
  ...
  [ 89.96   7.88  71.42 ...  33.98  55.04 112.28]
  [ 46.94  57.38  77.36 ...  14.18  59.    85.64]
  [111.56  99.5   97.16 ...  37.4   42.08 103.28]]

 ...

 [[  9.14 105.62  25.16 ...   8.6   35.78  89.96]
  [ 53.78  81.14  -1

/var/folders/34/tcqt3fyx41z17xmtzkx9_6_r0000gn/T/ipykernel_88287/435197928.py:3: RuntimeWarning: divide by zero encountered in log
  heat_stress = np.exp(np.log(climate_data + 10 ))
/var/folders/34/tcqt3fyx41z17xmtzkx9_6_r0000gn/T/ipykernel_88287/435197928.py:3: RuntimeWarning: invalid value encountered in log
  heat_stress = np.exp(np.log(climate_data + 10 ))


* Math & Stats:

  - Find the absolute highest and lowest valid temperatures recorded anywhere on the grid during the month (np.nanmax, np.nanmin).

   - Calculate the average temperature for each specific sensor location across the entire month (using np.nanmean across the "Days" axis). This will collapse your 3D array into a 2D map showing the baseline climate for each coordinate!

In [14]:
temp_highest = np.nanmax(climate_data)
temp_lower = np.nanmin(climate_data)

temp_average = np.nanmean(climate_data)

print(temp_highest)
print(temp_lower)
print(temp_average)

45.0
-99.0
12.217255973715652
